$background = 0b0f11
$onBackground = dee7ec
$surface = 0b0f11
$surfaceDim = 0b0f11
$surfaceBright = 252d31
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0f1417
$surfaceContainer = 141b1e
$surfaceContainerHigh = 192124
$surfaceContainerHighest = 1f272b
$onSurface = dee7ec
$surfaceVariant = 1f272b
$onSurfaceVariant = a3acb1
$outline = 6e777b
$outlineVariant = 41494d
$inverseSurface = f7fafc
$inverseOnSurface = 525658
$shadow = 000000
$scrim = 000000
$surfaceTint = a1cde1
$primary = a1cde1
$primaryDim = 93bfd3
$onPrimary = 164556
$primaryContainer = 2b5869
$onPrimaryContainer = bdeafe
$inversePrimary = 396576
$primaryFixed = bae6fb
$primaryFixedDim = acd8ec
$onPrimaryFixed = 124353
$onPrimaryFixedVariant = 335f70
$secondary = b3cad5
$secondaryDim = a6bcc7
$onSecondary = 2e434c
$secondaryContainer = 293e47
$onSecondaryContainer = acc3ce
$secondaryFixed = cfe6f1
$secondaryFixedDim = c1d8e3
$onSecondaryFixed = 2d424b
$onSecondaryFixedVariant = 495f68
$tertiary = d4dfff
$tertiaryDim = bfd2fd
$onTertiary = 3e5074
$tertiaryContainer = bfd2fd
$onTertiaryContainer = 35476b
$tertiaryFixed = bfd2fd
$tertiaryFixedDim = b2c4ee
$onTertiaryFixed = 223457
$onTertiaryFixedVariant = 3f5075
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 527d8f
$secondaryPaletteKeyColor = 657a84
$tertiaryPaletteKeyColor = 65779e
$neutralPaletteKeyColor = 74787a
$neutralVariantPaletteKeyColor = 6f787d
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 527d8f
$secondary_paletteKeyColor = 657a84
$tertiary_paletteKeyColor = 65779e
$neutral_paletteKeyColor = 74787a
$neutral_variant_paletteKeyColor = 6f787d
$term0 = 343434
$term1 = 8383ff
$term2 = 3fe0ea
$term3 = 75fcdd
$term4 = 7ab3c6
$term5 = 7aaee9
$term6 = 82d6e5
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 3ff3ff
$term11 = c9fff3
$term12 = a5c6d0
$term13 = a2c0f7
$term14 = 89eaf9
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = c3e0ff
$mauve = 7cc8ff
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d0f9f4
$green = 8deeff
$teal = a4eaff
$sky = a0e5ff
$sapphire = 7dd2f5
$blue = 6dc7f4
$lavender = 95d4fc
$klink = 1192bc
$klinkSelection = 0f92bb
$kvisited = 0088ca
$kvisitedSelection = 0088c9
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bad1
$kpositiveSelection = 00bad0
$text = dee7ec
$subtext1 = a3acb1
$subtext0 = 6e777b
$overlay2 = 60686c
$overlay1 = 51595c
$overlay0 = 444a4d
$surface2 = 363c3f
$surface1 = 292e30
$surface0 = 1a1e21
$base = 0b0f11
$mantle = 0b0f11
$crust = 0a0e10
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
