-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        zoom_factor = 1.0,
    },
    decoration = {
        active_opacity = 1.0,
        dim_inactive = false,
        inactive_opacity = 1.0,
        rounding = 17,
    },
    general = {
        border_size = 2,
        col = {
            active_border = "0xffffffff",
        },
        gaps_in = 3,
        gaps_out = 9,
        resize_on_border = true,
    },
    input = {
        accel_profile = "",
        follow_mouse = 1,
        mouse_refocus = true,
        natural_scroll = false,
        scroll_factor = 1.0,
        sensitivity = -0.0,
        touchpad = {
            scroll_factor = 1.0,
        },
    },
    misc = {
        vrr = 0,
    },
})
