-- Generated by HyprMod

-- Settings
hl.config({
    input = {
        accel_profile = "",
        follow_mouse = 1,
        mouse_refocus = true,
        natural_scroll = false,
        scroll_factor = 1.0,
        sensitivity = -0.0,
        touchpad = {
            scroll_factor = 1.0,
        },
    },
})
