-- Generated by nwg-displays on 2026-08-11 at 00:18:51. Do not edit manually.
-- Positions corrected: HDMI-A-1 restored to primary origin 0x0

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.99",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@74.0",
    position = "1920x-420",
    scale = 1,
    transform = 3
})

